[package]
name = "binary-inspector-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.9"

[dependencies.binary-inspector]
path = ".."

[[bin]]
name = "parse_elf"
path = "fuzz_targets/parse_elf.rs"
test = false
doc = false

